version: "3"

services:
  node:
    image: node:16
    working_dir: /app
    volumes:
      - ./:/app
    container_name: desafio_xp
    tty: true
    stdin_open: true
    command: bash
    restart: always
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      JWT_SECRET: secretJWT
  db:
    container_name: db_desafio_xp
    image: mysql:8.0.21
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password

networks:
  default:
    name: desafio_xp_net